name: deployment
on:
  push:
    branches: main
jobs:
  build_and_installation:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
    steps:
      - name: get the codes
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm install
      - name: build the project
        run: tsc --build
      - name: produce the artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist
  deploy:
    runs-on: self-hosted
    needs: build_and_installation
    steps:
      - name: install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: download the artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
