name: deployment
on:
  push:
    branches: main
jobs:
  build_and_installation:
    runs-on: ubuntu-latest
    steps:
      - name: get the codes
        uses: actions/checkout@v4
      - name: build the project
        run: tsc --build
      - name: produce the artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
            dist
            package.json
            package-lock.json
            prisma
  deploy:
    runs-on: self-hosted
    needs: build_and_installation
    steps:
      - name: install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: download the artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: create .env
        run: |
          touch .env
          echo "DATABASE_URL=${{secrets.DATABASE_URL}}" > .env
      - name: install
        run: npm install
      - name: restart pm2
        run: pm2 restart app
